spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5169/oauth2
    username: oauth2
    password: oauth2
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show_sql: true

logging:
  level:
    org.springframework.security: debug

server:
  port: 9999
